3.0.2
paysera/lib-php-cs-fixer-config pull request #45
Opened 2024-10-18 12:39 UTC by viktorkulahin

- ChainedMethodCallsFixer refactored for the proper whitespaces, new lines, etc.
- DefaultValuesInConstructorFixer refactored
- ConditionResultsFixer fixed a bug when trying to get not existing token index+1
- TypeHintingArgumentsFixer to work correctly with nullable (?type) and other arguments.
- ChainedMethodCallsFixerTest - test cases added
- DefaultValuesInConstructorFixerTest - test cases added

2024-10-18 14:32 UTC, mSprunskas requested changes

2024-10-18 15:52 UTC, viktorkulahin commented on src/Fixer/PhpBasic/CodeStyle/DefaultValuesInConstructorFixer.php
> +        if ($token->equals(';')) {
Fixed

2024-10-18 15:52 UTC, viktorkulahin commented on src/Fixer/PhpBasic/Feature/TypeHintingArgumentsFixer.php
> +                    $nullableFound = false;
Fixed

2024-10-22 07:00 UTC, mSprunskas approved these changes

2024-10-22 07:00 UTC, merged